version: "3.9"
services:
  postgres:
    image: postgres
    container_name: db
    env_file:
      - ./.env
    volumes:
      - ./deploy/db:/docker-entrypoint-initdb.d
      - ./demodb-data:/var/lib/postgresql/data 
    ports:
      - 5432:5432